Causes an issue with cloning the repo. No longer needed and saved a local copy.
Cloning into 'C:\Users\ADC\Documents\GitHub\hmpps-cr-ancillary-cporacle'...
remote: Enumerating objects: 425, done.        
remote: Counting objects: 100% (425/425), done.        
remote: Compressing objects: 100% (306/306), done.        
remote: Total 425 (delta 228), reused 276 (delta 93), pack-reused 0        
Receiving objects: 100% (425/425), 8.23 MiB | 323.00 KiB/s, done.
Resolving deltas: 100% (228/228), done.
error: invalid path 'docs/Migrating SQL Server to Amazon RDS using native backup and restore | AWS Database Blog.pdf'
fatal: unable to checkout working tree